version: '3'
services:
    nginx:
        container_name: nginx
        image: nginx
        # networks:
        #     - mynet
        volumes:
            - ./code:/code
            - ./config/default.conf:/etc/nginx/conf.d/default.conf:ro
            # - ./config/nginx.conf:/etc/nginx/nginx.conf:ro
        ports:
            - 80:80
            - 443:443
            
    php-fpm:
        container_name: php-fpm
        image: php:7.4.3-fpm
        # networks:
        #     - mynet
        volumes:
            - ./code:/code

    mongo:
        container_name: mongo
        image: mongo
        expose:
            - 27017
        # volumes:
            # - ./db/mongo:/data/db
            # - ./config/mongod.conf:/etc/mongod.conf
    
# networks:
#     mynet:
#         # 使用外部自訂網路
#         external: true
