version: '3'
services:
  nginx:
    container_name: nginx
    image: nginx
    volumes:
      - ./api_code:/usr/share/nginx/html/code
      - ./config/api_code.conf:/etc/nginx/conf.d/api_code.conf:ro
      # - ./config/default.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - 80:80
      - 443:443
  php-fpm:
    container_name: php-fpm
    image: php:7.4.3-fpm
    volumes:
      - ./api_code:/usr/share/nginx/html/code
  # mongo:
  #   container_name: mongo
  #   image: mongo
  #   expose:
  #     - 27017
  #   volumes:
  #     - ./docker/db/mongo:/data/db
  #     - ./docker/config/mongod.conf:/etc/mongod.conf
